version: '3.8'

services:
  db:
    image: supabase/postgres:15.1.0.118
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  studio:
    image: supabase/studio:20240325
    restart: unless-stopped
    environment:
      - SUPABASE_URL=http://localhost:8000
      - SUPABASE_DB_HOST=db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=postgres
      - SUPABASE_DB_NAME=postgres
    ports:
      - "5433:3000"
    depends_on:
      - db

volumes:
  db:
