services:
  app:
    image: docker.io/bbging/stundenzettel:latest
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://kong:8000
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    depends_on:
      - supabase-db
      - supabase-studio
      - kong

  supabase-db:
    image: supabase/postgres:15.1.0.118
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./supabase/volumes/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  supabase-studio:
    image: supabase/studio:latest
    restart: unless-stopped
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_DB_HOST=supabase-db
      - SUPABASE_DB_PORT=5432
      - SUPABASE_DB_USER=postgres
      - SUPABASE_DB_PASSWORD=postgres
      - SUPABASE_DB_NAME=postgres
    ports:
      - "5433:3000"
    depends_on:
      - supabase-db
      - kong

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/var/lib/kong/kong.yml
      - KONG_DNS_ORDER=LAST,A,CNAME
      - KONG_PLUGINS=request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction
      - KONG_NGINX_PROXY_PROXY_BUFFER_SIZE=160k
      - KONG_NGINX_PROXY_PROXY_BUFFERS=64 160k
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9zZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - DASHBOARD_USERNAME=supabase
      - DASHBOARD_PASSWORD=this_password_is_insecure_and_should_be_updated
    entrypoint: bash -c 'eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    ports:
      - "8000:8000"
    depends_on:
      - supabase-db

  auth:
    image: supabase/gotrue:v2.180.0
    restart: unless-stopped
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - API_EXTERNAL_URL=http://localhost:9999
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:postgres@supabase-db:5432/postgres
      - GOTRUE_SITE_URL=http://localhost:3000
      - GOTRUE_URI_ALLOW_LIST=http://localhost:3000
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_JWT_ADMIN_ROLES=service_role
      - GOTRUE_JWT_AUD=authenticated
      - GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - GOTRUE_EXTERNAL_EMAIL_ENABLED=true
      - GOTRUE_MAILER_AUTOCONFIRM=true
    depends_on:
      - supabase-db

  rest:
    image: postgrest/postgrest:v13.0.7
    restart: unless-stopped
    environment:
      - PGRST_DB_URI=postgres://authenticator:postgres@supabase-db:5432/postgres
      - PGRST_DB_SCHEMAS=public,graphql_public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - PGRST_DB_USE_LEGACY_GUCS=false
      - PGRST_APP_SETTINGS_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - PGRST_APP_SETTINGS_JWT_EXP=3600
    depends_on:
      - supabase-db

volumes:
  db: