services:
  app:
    image: docker.io/rebelein/stundenzettel:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://192.168.178.41:8000  # Passe an deine lokale Supabase an
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=dein_echter_api_key  # Ersetze mit deinem echten Key